### ISSUE TITLE
Possible to use with contentEditable?

### ISSUE THREAD

**Issue by brandondurham** [davidtheclark/focus-trap-react#43]
I’ve build a tool that allows you to try out a bunch of different webfonts in the browser. You can change the font family or style; set the size, leading, tracking, and margins; and toggle on and off any of its stylistic sets or open type features.

The editor itself is a `<div />` with `contentEditable` turned on and `role` set to `textbox`. This is the element I need to trap focus on conditionally, but I’m seeing the error that says:

> `Error: You can't have a focus-trap without at least one focusable element`

Is there any way to use focus-trap-react with a contentEditable element?

**Comment by davidtheclark** [comment]
Did you try setting a `tabIndex` on the content-editable element?

**Comment by stefcameron** [comment]
@brandondurham Based on https://github.com/davidtheclark/tabbable/blob/master/src/index.js#L10, focus-trap-react should work fine with nodes that are `contenteditable`, provided they also have a `tabIndex`. You can't set focus to a `div`, for example, unless it has a [tabIndex](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/tabindex) attribute.

Since there's been no response since David commented over a year ago, I'm closing this. Feel free to re-open if it's still an issue.
