### ISSUE TITLE
`this.node.current` is null.

### ISSUE THREAD

**Issue by asaadmahmood** [davidtheclark/focus-trap-react#50]
I have a code like this in react:
```
constructor(props) {
    super(props);
    this.node = React.createRef();
}
```

And then in the return call, I have this:
```
<FocusTrap>
    <ul
        ref={this.node}
    >
        {children}
    </ul>
</FocusTrap>
```

If I go ahead and fetch `this.node.current`, I get `null`.
However, if I do it without the `<FocusTrap>` everything works fine.

Any idea why `<FocusTrap>` would be messing with the node?

If however I do this, then it fetches the `this.node.current`:
```
<FocusTrap>
    <div>
        <ul
            ref={this.node}
        >
            {children}
        </ul>
    </div>
</FocusTrap>
```
I do not want to give that extra containing class, as it is messing up the layout.

**Comment by adamyonk** [comment]
Having the same issue with a `ref` on the first child of `<FocusTrap>`.

**Comment by stefcameron** [comment]
I just ran into the same issue. My child component cannot get a ref unless `<FocusTrap>` is at least one level above.

**Comment by Shou** [comment]
In my case I had to use two different elements to get around this, e.g. `<main><div ref={...}>{...}</div></main>`

**Comment by scottrippey** [comment]
Looks to me like this is the culprit:
https://github.com/davidtheclark/focus-trap-react/blob/master/src/focus-trap-react.js#L82-L84
```
      if (typeof child.ref === 'function') {
        child.ref(element);
      }
```
It's not taking into account a "mutable ref object", so that's why it's not working for the direct child.

So, as an alternative workaround, you can use a "function ref" like it expects.  But I think it'll be pretty trivial to create a PR to fix this one.
